site_name: Vex Panel
theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.tabs
    - navigation.top
    
repo_name: GallearTech/vexpanel-docs
repo_url: https://github.com/GallearTech/vexpanel-docs
edit_uri: 'https://github.com/GallearTech/vexpanel-docs/edit/master/docs'

google_analytics: 
  - 'UA-131385947-5'
  - 'auto'

nav:
  - 'Home':
    - 'Welcome': index.md

plugins:
  - search
  - minify:
      minify_html: true

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/GallearTech/'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true